# Generated by Django 2.0.2 on 2018-03-12 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_key', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='LogTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateTimeField(verbose_name='Time of action')),
                ('action', models.CharField(max_length=50)),
                ('key_ceil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doors.KeyCell')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(decimal_places=0, max_digits=3)),
                ('floor', models.DecimalField(decimal_places=0, max_digits=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('document_number', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=16)),
                ('pin_code', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='logtable',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doors.User'),
        ),
        migrations.AddField(
            model_name='keycell',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doors.Room'),
        ),
    ]
