# Generated by Django 2.0.2 on 2018-03-16 12:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoorsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('last_name', models.CharField(max_length=100, verbose_name='Отчество')),
                ('document_number', models.CharField(max_length=25, verbose_name='Номер документа')),
                ('phone_number', models.CharField(max_length=16, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=200, unique=True, verbose_name='e-mail')),
                ('pin_code', models.CharField(max_length=4, verbose_name='PIN-код')),
                ('jwt_secret', models.UUIDField(default=uuid.uuid4)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='KeyCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_key', models.BooleanField(verbose_name='Ключ в ячейке?')),
            ],
            options={
                'verbose_name': 'Ячейка',
                'verbose_name_plural': 'Ячейки',
            },
        ),
        migrations.CreateModel(
            name='LogTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateTimeField(verbose_name='Время')),
                ('event', models.CharField(choices=[('get_key', 'Взял ключ'), ('return_key', 'Вернул ключ')], max_length=50, verbose_name='Событие')),
                ('key_ceil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doors.KeyCell')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(decimal_places=0, max_digits=3)),
                ('floor', models.DecimalField(decimal_places=0, max_digits=1)),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('last_name', models.CharField(max_length=100, verbose_name='Отчество')),
                ('document_number', models.CharField(max_length=25, verbose_name='Номер документа')),
                ('phone_number', models.CharField(max_length=16, verbose_name='Номер телефона')),
                ('email', models.CharField(default='', max_length=200, verbose_name='e-mail')),
                ('pin_code', models.CharField(max_length=4, verbose_name='PIN-код')),
                ('jwt_secret', models.UUIDField(default=uuid.uuid4)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.AddField(
            model_name='logtable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doors.User'),
        ),
        migrations.AddField(
            model_name='keycell',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doors.Room'),
        ),
    ]
