# Generated by Django 2.0.2 on 2018-03-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0002_auto_20180312_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keycell',
            options={'verbose_name': 'Ячейка', 'verbose_name_plural': 'Ячейки'},
        ),
        migrations.AlterModelOptions(
            name='logtable',
            options={'verbose_name': 'Лог', 'verbose_name_plural': 'Логи'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Кабинет', 'verbose_name_plural': 'Кабинеты'},
        ),
        migrations.RenameField(
            model_name='logtable',
            old_name='action',
            new_name='event',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=200, verbose_name='e-mail'),
        ),
    ]
