# Generated by Django 2.0.2 on 2018-03-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0002_auto_20180316_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doorsuser',
            name='staff',
            field=models.BooleanField(default=False, verbose_name='Доступ к админке?'),
        ),
    ]
