# Generated by Django 2.0.2 on 2018-03-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0003_auto_20180312_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logtable',
            name='event',
            field=models.CharField(choices=[('get_key', 'Взял ключ'), ('return_key', 'Вернул ключ')], max_length=50),
        ),
    ]
