# Generated by Django 2.0.2 on 2018-04-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0003_auto_20180316_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.DecimalField(decimal_places=0, max_digits=1, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Номер кабинета'),
        ),
    ]
