# Generated by Django 2.0.2 on 2018-03-12 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0004_auto_20180312_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logtable',
            name='key_ceil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doors.KeyCell'),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doors.User'),
        ),
    ]
