# Generated by Django 2.0.2 on 2018-04-07 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0005_scheduleitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScheduleItem',
            new_name='Lesson',
        ),
    ]
