# Generated by Django 2.0.2 on 2018-04-08 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0008_keycell_user_who_get'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keycell',
            name='user_who_get',
        ),
    ]
