# Generated by Django 2.0.2 on 2018-04-08 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0010_keycell_user_who_get'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keycell',
            name='user_who_get',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто взял ключ'),
        ),
    ]
